### ISSUE TITLE
[1.19.2][kubejsprojecte-1.2] setPlayerEMC does the same as addPlayerEMC

### ISSUE THREAD

**Issue by MrNovado** [BobVarioa/kjsprojecte#3]
A typo?

[KubeJSProjectEPlugin.java#L40](https://github.com/BobVarioa/kjsprojecte/blob/main/src/main/java/com/bobvarioa/kubejsprojecte/kubejs/KubeJSProjectEPlugin.java#L40)
```java
public void setPlayerEMC(Player player, String num) {
            if (player == null) return;
            var cap = player.getCapability(PECapabilities.KNOWLEDGE_CAPABILITY);
            if (cap.isPresent()) {
                var emc = cap.resolve().get();
                emc.setEmc(emc.getEmc().add(new BigDecimal(num).toBigInteger()));
            }
        }
```
```java
// gets current and then adds `num` on top
emc.setEmc(emc.getEmc().add(new BigDecimal(num).toBigInteger()));
```

**Comment by MrNovado** [comment]
Also, `transmutation_table` does not update its `emc` balance after setting/adding emc through KubeJS. 
Meaning, it displays old emc balance until a transaction is made (buying/selling an item).
Any chance `projectE` has some sort of `refresh` method to push after setting `emc`?

**Comment by MrNovado** [comment]
Also, any chance bumping this to 1.20.1 pretty please? :3

**Comment by BobVarioa** [comment]
The first issue now has been fixed, and the second is out of my control. Run a `/reload` after a `/kubejs reload server_scripts` to refresh things like that, just as you would with recipes.
